Include new dates fields in transactions
devengoapp/devengo-ruby pull request #12
Opened 2023-03-17 10:10 UTC by TechiRexach

Includes the dates fields for transactions of `created_at` and `final_at`.

2023-03-17 10:52 UTC, Nachooc5 approved these changes

2023-03-17 11:56 UTC, Nachooc5 requested changes

2023-03-17 11:56 UTC, Nachooc5 commented on spec/fixtures/responses/transactions/find/success.http
> +}
Let's keep the line breaks, please 🙏

2023-03-17 11:56 UTC, Nachooc5 commented on spec/fixtures/responses/transactions/list/success.http
> +}
Same here: https://github.com/devengoapp/devengo-ruby/pull/12/files#r1140139343

2023-03-17 15:52 UTC, Nachooc5 approved these changes

2023-03-22 14:16 UTC, Nachooc5 approved these changes

2023-03-22 16:28 UTC, IvanGuardado approved these changes

2023-03-28 14:34 UTC, merged