Add error field to webhook response
devengoapp/devengo-ruby pull request #13
Opened 2023-03-22 12:51 UTC by TechiRexach

Self descriptive.

2023-03-22 12:52 UTC, carloslopdev approved these changes

2023-03-22 13:34 UTC, Nachooc5 approved these changes

2023-03-23 10:20 UTC, Nachooc5 commented on spec/devengo/api/webhook_requests_service_spec.rb
> +      expect(instance_methods_count(webhook_request.response)).to eq 8
We need add too expect to error field

2023-03-23 10:21 UTC, Nachooc5 requested changes

2023-03-23 10:42 UTC, Nachooc5 approved these changes

2023-03-23 10:45 UTC, merged